### ISSUE TITLE
buggy subscribe link

### ISSUE THREAD

**Issue by dcxSt** [merny93/blog#1]
When I hit the subscribe button, I got this screen full of raw HTML with the error message 

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
```

<img width="1440" alt="Screen Shot 2023-03-06 at 10 31 44 AM" src="https://user-images.githubusercontent.com/21654151/223155967-ac1ab12f-a5f8-4086-8966-952791cd8a2a.png">

**Comment by dcxSt** [comment]
i use brave browser, a chromium derivative

**Comment by merny93** [comment]
Thanks, I never finished configuring the default jekyll theme. Will fix (probably by removing the button ;) )

**Comment by merny93** [comment]
Deleted buggy link in commit c852ae0
